#!/usr/bin/env bash
#MISE description="Deploy contract"
#MISE dir="contracts"
#MISE quiet=true

contract() {
  PS3="Deploy: "
  select circuit in $(ls -1 "$MISE_CONFIG_ROOT/contracts/src/" | sed 's/\..*$//'); do
    echo "$circuit"
    break
  done
}

network() {
  PS3="On: "
  select network in anvil sepolia; do
    echo $network
    break
  done
}

main() {
  script="$(contract)Script"
  network=$(network)
  echo "Deploying $contract to $network"
  case $network in
  anvil)
    mise r deploy.sha256.anvil
    break
    ;;
  sepolia)
    forge script \
      "$script" \
      --broadcast \
      --chain sepolia \
      --rpc-url $SEPOLIA_RPC_URL \
      --private-key $DEV_PKEY \
      --verify \
      -vvvv \
      --interactives 1
    ;;
  esac
}

main
