#!/usr/bin/env bash
set -eu

ORANGE="\033[33m"
RED="\033[31m"
RESET="\033[0m"

log() {
  printf "%b\n" "$1"
}

install_mise() {
  curl https://mise.run | sh
  echo "✅ Installed ${ORANGE}mise$RESET"
}

maybe_install_mise() {
  if ! command -v mise >/dev/null; then
    install_mise
  else
    log "✅ ${ORANGE}mise$RESET is already installed"
  fi
}

use_convco_as_git_editor_only_on_main() {
  cat >.git/hooks/prepare-commit-msg <<'EOF'
#!/bin/sh

if [ "$(git rev-parse --abbrev-ref HEAD)" = "main" ]; then
    git config --local core.editor "convco commit"
else
    default_editor=$(git config --local --get sequence.editor || git config --global --get core.editor || echo "$EDITOR" || command -v nvim || command -v vim || command -v vi || command -v nano)

    if [ -n "$default_editor" ]; then
        git config --local core.editor "$default_editor"
    else
        echo "No default editor found. Please set one in your git config or set the EDITOR environment variable."
    fi
fi

if [ -z "$(git config --local --get sequence.editor)" ]; then
    editor=$(git config --global --get core.editor || echo "$EDITOR" || command -v nvim || command -v vim || command -v vi || command -v nano)
    if [ -n "$editor" ]; then
        git config --local sequence.editor "$editor"
    else
        echo "No default editor found. Please set one in your git config or set the EDITOR environment variable."
    fi
fi
EOF

  chmod +x .git/hooks/prepare-commit-msg
}

activate_environment() {
  # Check if the shell is interactive by testing if stdin is a terminal
  if [ -t 0 ]; then
    mise activate
  else
    # non interactive shell (cza cli)
    mise activate bash --shims
  fi
}

main() {
  maybe_install_mise
  mise trust
  mise install >/dev/null 2>&1 && log "✅ Installed dev tools and runtimes"

  # Activate the environment based on interactivity.
  activate_environment

  use_convco_as_git_editor_only_on_main
  hk install >/dev/null && log "✅ Configured git hooks"
  bun install >/dev/null && log "✅ Installed node deps"
}

main
