name: Release PRs

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - run: bun i
      - run: bun publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          monorepo-tags: true
          token: ${{ secrets.GITHUB_TOKEN }}
          path: templates
